"""
pre.py generated by lmgc90_core — project 'engine_demo'
dimension = 2    units = SI
bodies    = 4  (AoS 4 + SoA 0)
"""
from pylmgc90 import pre
import numpy as np

mats   = pre.materials()
mods   = pre.models()
bodies = pre.avatars()
tacts  = pre.tact_behavs()
sees   = pre.see_tables()
posts  = pre.postpro_commands()

# --- materials ---
mat_STEEL = pre.material(name='STEEL', materialType='RIGID', density=7800.0)
mats.addMaterial(mat_STEEL)
mat_BETON = pre.material(name='BETON', materialType='RIGID', density=2400.0)
mats.addMaterial(mat_BETON)

# --- models ---
mod_rigid = pre.model(name='rigid', physics='MECAx', element='Rxx2D', dimension=2)
mods.addModel(mod_rigid)

# --- avatars (individually edited) ---
av_824c7758 = pre.smoothWall(l=2.0, h=0.1, center=[0.0, -0.05], model=mod_rigid, material=mat_STEEL, color='GRAYx', nb_polyg=16)
bodies.addAvatar(av_824c7758)

av_6bcc3824 = pre.rigidDisk(r=0.08, center=[-0.4, 0.2], model=mod_rigid, material=mat_BETON, color='BLUEx')
bodies.addAvatar(av_6bcc3824)

av_be4d244f = pre.rigidDisk(r=0.08, center=[0.0, 0.25], model=mod_rigid, material=mat_BETON, color='BLUEx')
bodies.addAvatar(av_be4d244f)

av_ae1d3331 = pre.rigidDisk(r=0.08, center=[0.4, 0.30000000000000004], model=mod_rigid, material=mat_BETON, color='BLUEx')
bodies.addAvatar(av_ae1d3331)

# --- contact laws ---
law_st_bt = pre.tact_behav(name='st_bt', law='IQS_CLB', fric=0.3)
tacts.addBehav(law_st_bt)

# --- see tables ---
see_0 = pre.see_table(CorpsCandidat='RBDY2', candidat='DISKx', colorCandidat='BLUEx', CorpsAntagoniste='RBDY2', antagoniste='JONCx', colorAntagoniste='GRAYx', behav='st_bt', alert=0.05)
sees.addSeeTable(see_0)

pre.writeDatbox(
    dim=2, mats=mats, mods=mods, tacts=tacts,
    sees=sees, bodies=bodies, post=posts,
)
