"""Emit a chipy `command.py`. Solver defaults match LMGC90 GUI 0.5.x."""
from __future__ import annotations

from typing import Any

from .project import Project

_DEFAULTS: dict[str, Any] = {
    "dt": 1e-3,
    "nb_steps": 1000,
    "theta": 0.5,
    "tol": 1.666e-4,
    "relax": 1.0,
    "norm": "Quad ",
    "gs_it1": 50,
    "gs_it2": 1000,
    "solver_type": "Stored_Delassus_Loops         ",
    "freq_write": 50,
    "freq_display": 50,
    "dimension": None,
}


def emit_chipy(project: Project, **params) -> str:
    p = dict(_DEFAULTS)
    p.update(params)
    dim = int(p["dimension"] or project.dimension)
    rbdy = "RBDY2" if dim == 2 else "RBDY3"
    visu = "visuAvatars" if dim == 2 else "visuAvatars"

    lines = [
        '"""',
        f"command.py generated by lmgc90_core — project {project.name!r}",
        f"dt={p['dt']}  steps={p['nb_steps']}  solver={p['solver_type'].strip()}",
        '"""',
        "from pylmgc90 import chipy",
        "",
        "chipy.Initialize()",
        f"chipy.SetDimension({dim})",
        "chipy.checkDirectories()",
        "chipy.utilities_DisableLogMes()",
        "",
        "chipy.ReadDatbox(deformable=False)",
        "",
        f"chipy.{rbdy}_LoadTactors()",
        "chipy.LoadTactors()",
        "chipy.ReadIni()",
        "",
        f"chipy.SetTimeStep({p['dt']})",
        f"chipy.SetThetaIntegrator({p['theta']})",
        "chipy.ComputeMass()",
        "",
        f"chipy.OpenDisplayFiles()",
        "chipy.WriteDisplayFiles(0)",
        "",
        "chipy.utilities_logMes('STARTING TIME LOOP')",
        f"for k in range(1, {int(p['nb_steps'])} + 1):",
        "    chipy.IncrementStep()",
        f"    chipy.{rbdy}_ComputeFext()",
        f"    chipy.{rbdy}_ComputeBulk()",
        "    chipy.ComputeFreeVelocity()",
        "    chipy.SelectProxTactors()",
        "    chipy.RecupRloc()",
        f"    chipy.ExSolver({p['solver_type']!r}, {p['norm']!r}, {p['tol']}, {p['relax']}, {p['gs_it1']}, {p['gs_it2']})",
        "    chipy.StockRloc()",
        "    chipy.ComputeDof()",
        f"    chipy.{rbdy}_ComputeRFext()",
        "    chipy.UpdateStep()",
        f"    if k % {int(p['freq_write'])} == 0:",
        "        chipy.WriteOut(1)",
        f"    if k % {int(p['freq_display'])} == 0:",
        "        chipy.WriteDisplayFiles(1)",
        "",
        "chipy.WriteLast()",
        "chipy.CloseDisplayFiles()",
        "chipy.Finalize()",
    ]
    return "\n".join(lines) + "\n"
