"""Simulation pipeline as data, plus a Slurm script — not a YAML DSL."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, Optional

from .project import Project

Backend = Literal["local", "slurm"]


@dataclass
class Step:
    name: str
    params: dict[str, Any] = field(default_factory=dict)


@dataclass
class Pipeline:
    steps: list[Step] = field(default_factory=list)
    backend: Backend = "local"

    @classmethod
    def standard(cls, *, dt: float = 1e-3, nb_steps: int = 5000,
                 backend: Backend = "local") -> Pipeline:
        return cls(
            backend=backend,
            steps=[
                Step("write_pre"),
                Step("write_chipy", {"dt": dt, "nb_steps": nb_steps}),
                Step("write_datbox"),
                Step("run", {"backend": backend}),
            ],
        )

    def to_dict(self) -> dict:
        return {
            "backend": self.backend,
            "pipeline": [{"step": s.name, "params": s.params} for s in self.steps],
        }


def render_sbatch(
    project: Project,
    *,
    job_name: Optional[str] = None,
    partition: str = "cpu",
    account: Optional[str] = None,
    time: str = "04:00:00",
    ntasks: int = 1,
    cpus_per_task: int = 1,
    mem: str = "8G",
    workdir: str = "$SLURM_SUBMIT_DIR",
    module_load: tuple[str, ...] = ("python/3.11",),
    python: str = "python",
) -> str:
    name = job_name or project.name.replace(" ", "_")[:40]
    account_line = f"#SBATCH --account={account}" if account else "#SBATCH --account=_SET_ME_"
    modules = "\n".join(f"module load {m}" for m in module_load)
    return f"""#!/bin/bash
#SBATCH --job-name={name}
#SBATCH --partition={partition}
{account_line}
#SBATCH --time={time}
#SBATCH --ntasks={ntasks}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mem={mem}
#SBATCH --output={name}-%j.out
#SBATCH --error={name}-%j.err

set -euo pipefail
cd {workdir}

{modules}

# Generated by lmgc90_core for project {project.name!r}
# 1. Build DATBOX from the emitted pre.py (requires pylmgc90 on the node)
{python} pre.py
# 2. Run the computation
{python} command.py
"""
