"""Emit an auditable `pre.py`. This is the reproducibility artefact."""
from __future__ import annotations

from typing import Any

from .entities import Avatar, ContactLaw, GranuloConfig, Material, Model, VisibilityRule
from .population import ParticlePopulation
from .project import Project
from .types import AvatarType


def emit_pre(project: Project) -> str:
    w: list[str] = []
    def L(s: str = "") -> None:
        w.append(s)

    L('"""')
    L(f"pre.py generated by lmgc90_core — project {project.name!r}")
    L(f"dimension = {project.dimension}    units = {project.units.value}")
    L(f"bodies    = {project.n_bodies}  (AoS {len(project.avatars)} + SoA {sum(len(p) for p in project.populations)})")
    L('"""')
    L("from pylmgc90 import pre")
    L("import numpy as np")
    L()
    from .numpy_compat import PRE_PY_CROSS_PATCH
    for line in PRE_PY_CROSS_PATCH.strip("\n").splitlines():
        L(line)
    L()
    L("mats   = pre.materials()")
    L("mods   = pre.models()")
    L("bodies = pre.avatars()")
    L("tacts  = pre.tact_behavs()")
    L("sees   = pre.see_tables()")
    L("posts  = pre.postpro_commands()")
    L()

    L("# --- materials ---")
    for m in project.materials:
        L(_emit_material(m))
        L(f"mats.addMaterial(mat_{m.name})")
    L()
    L("# --- models ---")
    for m in project.models:
        L(_emit_model(m))
        L(f"mods.addModel(mod_{m.name})")
    L()

    L("# --- avatars (individually edited) ---")
    for av in project.avatars:
        L(_emit_avatar(av))
        if av.avatar_type == AvatarType.MESH_DEFORMABLE:
            L(_emit_mesh_contactors(av))
        L(f"bodies.addAvatar(av_{_ident(av.avatar_id)})")
        L()

    if project.populations:
        L("# --- particle populations (SoA → pre.rigidDisk/Sphere loop) ---")
        for pop in project.populations:
            L(_emit_population(pop))
            L()

    if project.laws:
        L("# --- contact laws ---")
        for law in project.laws:
            L(_emit_law(law))
            L(f"tacts.addBehav(law_{law.name})")
        L()

    if project.visibility:
        L("# --- see tables ---")
        for i, rule in enumerate(project.visibility):
            L(_emit_see(rule, i))
            L(f"sees.addSeeTable(see_{i})")
        L()

    if project.operations:
        L("# --- boundary conditions ---")
        for op in project.operations:
            L(_emit_dof(project, op))
        L()

    if project.postpro:
        L("# --- post-processing ---")
        for cmd in project.postpro:
            tgt = ""
            if cmd.target_type != "global" and cmd.target_value is not None:
                tgt = f", {cmd.target_type}={cmd.target_value!r}"
            L(f"posts.addCommand(pre.postpro_command(name={cmd.name!r}, step={cmd.step}{tgt}))")
        L()

    L("pre.writeDatbox(")
    L(f"    dim={project.dimension}, mats=mats, mods=mods, tacts=tacts,")
    L("    sees=sees, bodies=bodies, post=posts,")
    L(")")
    return "\n".join(w) + "\n"


def emit_equivalent(project: Project, obj) -> str:
    if isinstance(obj, Material):
        return _emit_material(obj)
    if isinstance(obj, Model):
        return _emit_model(obj)
    if isinstance(obj, Avatar):
        return _emit_avatar(obj)
    if isinstance(obj, ParticlePopulation):
        return _emit_population(obj)
    if isinstance(obj, ContactLaw):
        return _emit_law(obj)
    if isinstance(obj, VisibilityRule):
        return _emit_see(obj, 0)
    if isinstance(obj, GranuloConfig):
        return (
            f"# granulo {obj.container_type} n={obj.nb_particles} "
            f"r=[{obj.radius_min}, {obj.radius_max}] → ParticlePopulation"
        )
    return f"# no pre.* equivalent for {type(obj).__name__}"


def _ident(avatar_id: str) -> str:
    return avatar_id[:8]


def _kw(d: dict[str, Any]) -> str:
    parts = []
    for k, v in d.items():
        parts.append(f"{k}={v!r}")
    return ", ".join(parts)


def _emit_material(m: Material) -> str:
    extra = (", " + _kw(m.properties)) if m.properties else ""
    return (
        f"mat_{m.name} = pre.material(name={m.name!r}, "
        f"materialType={m.material_type.value!r}, density={m.density}{extra})"
    )


def _emit_model(m: Model) -> str:
    extra = (", " + _kw(m.options)) if m.options else ""
    return (
        f"mod_{m.name} = pre.model(name={m.name!r}, physics={m.physics!r}, "
        f"element={m.element!r}, dimension={m.dimension}{extra})"
    )


def _emit_avatar(av: Avatar) -> str:
    ident = _ident(av.avatar_id)
    mat, mod = f"mat_{av.material_name}", f"mod_{av.model_name}"
    c = av.center
    color = av.color
    t = av.avatar_type
    if t == AvatarType.RIGID_DISK:
        hollow = ", is_Hollow=True" if av.is_hollow else ""
        return (
            f"av_{ident} = pre.rigidDisk(r={av.radius}, center={c}, "
            f"model={mod}, material={mat}, color={color!r}{hollow})"
        )
    if t == AvatarType.RIGID_SPHERE:
        hollow = ", is_Hollow=True" if av.is_hollow else ""
        return (
            f"av_{ident} = pre.rigidSphere(r={av.radius}, center={c}, "
            f"model={mod}, material={mat}, color={color!r}{hollow})"
        )
    if t == AvatarType.RIGID_JONC:
        ax = av.axis or {}
        return (
            f"av_{ident} = pre.rigidJonc(axe1={ax.get('axe1')}, axe2={ax.get('axe2')}, "
            f"center={c}, model={mod}, material={mat}, color={color!r})"
        )
    if t == AvatarType.SMOOTH_WALL:
        wp = av.wall_params or {}
        return (
            f"av_{ident} = pre.smoothWall(l={wp.get('l')}, h={wp.get('h')}, "
            f"center={c}, model={mod}, material={mat}, color={color!r}, "
            f"nb_polyg={wp.get('nb_polyg', 10)})"
        )
    if t == AvatarType.ROUGH_WALL:
        wp = av.wall_params or {}
        return (
            f"av_{ident} = pre.roughWall(l={wp.get('l')}, r={wp.get('r')}, "
            f"center={c}, model={mod}, material={mat}, color={color!r}, "
            f"nb_vertex={wp.get('nb_vertex', 10)})"
        )
    if t == AvatarType.FINE_WALL:
        wp = av.wall_params or {}
        return (
            f"av_{ident} = pre.fineWall(l={wp.get('l')}, r={wp.get('r')}, "
            f"center={c}, model={mod}, material={mat}, color={color!r}, "
            f"nb_vertex={wp.get('nb_vertex', 10)})"
        )
    if t == AvatarType.RIGID_CLUSTER:
        return (
            f"av_{ident} = pre.rigidCluster(r={av.radius}, center={c}, "
            f"model={mod}, material={mat}, color={color!r}, nb_disk={av.nb_vertices})"
        )
    if t == AvatarType.RIGID_CYLINDER:
        wp = av.wall_params or {}
        hollow = ", is_Hollow=True" if av.is_hollow else ""
        return (
            f"av_{ident} = pre.rigidCylinder(r={av.radius}, h={wp.get('h')}, "
            f"center={c}, model={mod}, material={mat}, color={color!r}{hollow})"
        )
    if t == AvatarType.RIGID_PLAN:
        ax = av.axis or {}
        return (
            f"av_{ident} = pre.rigidPlan(center={c}, model={mod}, material={mat}, "
            f"color={color!r}, axe1={ax.get('axe1')}, axe2={ax.get('axe2')}, axe3={ax.get('axe3')})"
        )
    if t == AvatarType.RIGID_POLYGON:
        if av.generation_type == "regular":
            return (
                f"av_{ident} = pre.rigidPolygon(model={mod}, material={mat}, center={c}, "
                f"color={color!r}, generation_type='regular', nb_vertices={av.nb_vertices}, "
                f"radius={av.radius})"
            )
        return (
            f"av_{ident} = pre.rigidPolygon(model={mod}, material={mat}, center={c}, "
            f"color={color!r}, generation_type={av.generation_type!r}, "
            f"vertices=np.array({av.vertices}), radius={av.radius})"
        )
    if t == AvatarType.MESH_DEFORMABLE:
        mp = av.mesh_params or {}
        geom = mp.get("geom")
        if geom == "Rectangle":
            x0 = mp["cx"] - mp["lx"] / 2.0
            y0 = mp["cy"] - mp["ly"] / 2.0
            return (
                f"mesh_{ident} = pre.buildMesh2D({mp.get('mesh_type', '2T3')!r}, "
                f"{x0}, {y0}, {mp['lx']}, {mp['ly']}, {mp['nx']}, {mp['ny']})\n"
                f"av_{ident} = pre.buildMeshedAvatar(mesh=mesh_{ident}, model={mod}, material={mat})"
            )
        if geom == "Boîte (H8)":
            x0 = mp["cx"] - mp["lx"] / 2.0
            y0 = mp["cy"] - mp["ly"] / 2.0
            z0 = mp.get("cz", 0.0) - mp["lz"] / 2.0
            return (
                f"mesh_{ident} = pre.buildMeshH8({x0}, {y0}, {z0}, "
                f"{mp['lx']}, {mp['ly']}, {mp['lz']}, {mp['nx']}, {mp['ny']}, {mp['nz']})\n"
                f"av_{ident} = pre.buildMeshedAvatar(mesh=mesh_{ident}, model={mod}, material={mat})"
            )
        if geom == "Fichier externe":
            return (
                f"mesh_{ident} = pre.readMesh({mp.get('filepath', '')!r}, {mp.get('dim', 2)})\n"
                f"av_{ident} = pre.buildMeshedAvatar(mesh=mesh_{ident}, model={mod}, material={mat})"
            )
        return f"av_{ident} = None  # MESH_DEFORMABLE geom={geom!r} not emitted"
    return (
        f"# TODO {t.value}: av_{ident} — stored in .lmgc90, emit not yet specialised\n"
        f"av_{ident} = None"
    )


def _emit_mesh_contactors(av: Avatar) -> str:
    ident = _ident(av.avatar_id)
    lines = []
    for c in av.contactors:
        shape = c.get("shape")
        color = c.get("color", av.color)
        group = c.get("group")
        extra = f", group={group!r}" if group else ""
        lines.append(f"av_{ident}.addContactors(shape={shape!r}, color={color!r}{extra})")
    return "\n".join(lines)


def _emit_population(pop: ParticlePopulation) -> str:
    fn = {
        AvatarType.RIGID_DISK: "rigidDisk",
        AvatarType.RIGID_SPHERE: "rigidSphere",
        AvatarType.RIGID_DISCRETE: "rigidDiscreteDisk",
        AvatarType.RIGID_CLUSTER: "rigidCluster",
        AvatarType.RIGID_CYLINDER: "rigidCylinder",
    }.get(pop.avatar_type, "rigidDisk")
    extra = ""
    if pop.avatar_type == AvatarType.RIGID_CLUSTER:
        extra = f", nb_disk={pop.extra_params.get('nb_disk', 3)}"
    if pop.avatar_type == AvatarType.RIGID_CYLINDER:
        extra = f", h={pop.extra_params.get('h', 1.0)}"
    ident = pop.population_id[:12].replace("-", "_")
    return "\n".join([
        f"# population {pop.population_id}  n={len(pop)}  {pop.avatar_type.value}",
        f"centers_{ident} = np.array({pop.centers.tolist()})",
        f"radii_{ident}   = np.array({pop.radii.tolist()})",
        f"for _i, (_c, _r) in enumerate(zip(centers_{ident}, radii_{ident})):",
        f"    _body = pre.{fn}(r=float(_r), center=_c, model=mod_{pop.model_name}, "
        f"material=mat_{pop.material_name}, color={pop.color!r}{extra})",
        f"    bodies.addAvatar(_body)",
    ])


def _emit_law(law: ContactLaw) -> str:
    fric = f", fric={law.friction}" if law.friction is not None else ""
    extra = (", " + _kw(law.properties)) if law.properties else ""
    return (
        f"law_{law.name} = pre.tact_behav(name={law.name!r}, "
        f"law={law.law_type.value!r}{fric}{extra})"
    )


def _emit_see(rule: VisibilityRule, i: int) -> str:
    return (
        f"see_{i} = pre.see_table("
        f"CorpsCandidat={rule.candidate_body!r}, candidat={rule.candidate_contactor!r}, "
        f"colorCandidat={rule.candidate_color!r}, "
        f"CorpsAntagoniste={rule.antagonist_body!r}, antagoniste={rule.antagonist_contactor!r}, "
        f"colorAntagoniste={rule.antagonist_color!r}, "
        f"behav={rule.behavior_name!r}, alert={rule.alert})"
    )


def _emit_dof(project: Project, op) -> str:
    if op.target_type == "avatar":
        ident = _ident(str(op.target_value))
        target = f"av_{ident}"
    elif op.target_type == "group":
        ids = project.avatar_groups.get(str(op.target_value), [])
        if not ids:
            return f"# DOF on empty group {op.target_value!r}"
        ident = _ident(ids[0])
        target = f"av_{ident}  # group {op.target_value!r} — apply to each member"
    else:
        target = "bodies"
    params = ", ".join(f"{k}={v!r}" for k, v in op.parameters.items())
    if op.operation_type == "imposeDrivenDof":
        return f"{target}.imposeDrivenDof({params})"
    if op.operation_type == "imposeInitValue":
        return f"{target}.imposeInitValue({params})"
    if op.operation_type == "translate":
        return f"{target}.translate({params})"
    if op.operation_type == "rotate":
        return f"{target}.rotate({params})"
    return f"{target}.{op.operation_type}({params})"
