"""
pre.py generated by lmgc90_core — project 'wave1_box'
dimension = 2    units = SI
bodies    = 51  (AoS 11 + SoA 40)
"""
from pylmgc90 import pre
import numpy as np

mats   = pre.materials()
mods   = pre.models()
bodies = pre.avatars()
tacts  = pre.tact_behavs()
sees   = pre.see_tables()
posts  = pre.postpro_commands()

# --- materials ---
mat_STEEL = pre.material(name='STEEL', materialType='RIGID', density=7800.0)
mats.addMaterial(mat_STEEL)
mat_SAND = pre.material(name='SAND', materialType='RIGID', density=2500.0)
mats.addMaterial(mat_SAND)

# --- models ---
mod_rigid = pre.model(name='rigid', physics='MECAx', element='Rxx2D', dimension=2)
mods.addModel(mod_rigid)

# --- avatars (individually edited) ---
av_e7b5a684 = pre.smoothWall(l=2.0, h=0.08, center=[0.0, -0.04], model=mod_rigid, material=mat_STEEL, color='GRAYx', nb_polyg=16)
bodies.addAvatar(av_e7b5a684)

av_c64dff50 = pre.rigidDisk(r=0.06, center=[0.0, 0.3], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_c64dff50)

av_38a6e2c7 = pre.rigidDisk(r=0.06, center=[-0.15, 0.3], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_38a6e2c7)

av_b67407cc = pre.rigidDisk(r=0.06, center=[0.0, 0.3], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_b67407cc)

av_a6d9dffd = pre.rigidDisk(r=0.06, center=[0.15, 0.3], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_a6d9dffd)

av_e4a6c139 = pre.rigidDisk(r=0.06, center=[-0.15, 0.44999999999999996], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_e4a6c139)

av_3dc62bf1 = pre.rigidDisk(r=0.06, center=[0.0, 0.44999999999999996], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_3dc62bf1)

av_31da1325 = pre.rigidDisk(r=0.06, center=[0.15, 0.44999999999999996], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_31da1325)

av_d2047842 = pre.rigidDisk(r=0.06, center=[-0.15, 0.6], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_d2047842)

av_3caa3a09 = pre.rigidDisk(r=0.06, center=[0.0, 0.6], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_3caa3a09)

av_45ad859d = pre.rigidDisk(r=0.06, center=[0.15, 0.6], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_45ad859d)

# --- particle populations (SoA → pre.rigidDisk/Sphere loop) ---
# population pop_69c2dd2b827b4cc7b2fda6d6bc7b5b18  n=40  rigidDisk
centers_pop_69c2dd2b = np.array([[-0.10992544806013826, -0.1731609313007612], [0.47469281288228926, -0.2173063344908202], [0.02152512213241753, -0.08049388249168973], [-0.19103180092440886, -0.264946530225719], [-0.10444357894757128, 0.08400633499060595], [0.44093418766190173, -0.2720800787550845], [-0.29879679927533553, -0.2589542186749666], [0.25830586200381844, -0.1369289212182723], [-0.14021307350738976, 0.045814840797990364], [0.14151358950560333, 0.18326917057851222], [-0.11850706736007999, -0.13009736605832015], [0.0038029501945295863, 0.19468928637116217], [-0.4832771783646229, 0.14756902810579353], [-0.0064284400566038125, -0.22391115098559922], [0.471598413446888, 0.18380936082381416], [-0.21453477121442155, 0.19875066518116868], [0.24821795907661215, -0.19330452985973645], [-0.057211109929504955, 0.07616879914353214], [-0.29071895738221454, -0.18195382690725723], [0.4050025708181295, -0.15390437278315047], [-0.19649107340048932, 0.013332016770485067], [-0.23785320381001052, 0.02468463198252524], [0.34904452185927204, -0.17210119414472852], [0.3060357075271236, -0.133290952782835], [0.13031775544347823, 0.24760997383146616], [-0.47351545109602766, -0.19536965849501992], [-0.0531870482655481, -0.008877622550381825], [-0.128145430129894, -0.0742216199091886], [-0.3723793135039304, -0.0009242504262300666], [0.0620515900997094, 0.19985686128512015], [-0.11223088434404604, -0.2689956365283624], [0.29165620559034056, 0.1965570983155262], [0.10513658927751446, 0.18764978605006571], [0.3612666847869941, 0.254389875172537], [0.23236083732560453, 0.09864062469091966], [0.101823447758565, -0.20362581953678968], [-0.2123843978040043, -0.03484235312757733], [0.2827604679261685, -0.036340403897717644], [-0.2487324218289182, 0.07939979188914892], [-0.42478888818559557, -0.07131748055757386]])
radii_pop_69c2dd2b   = np.array([0.020118216247002565, 0.024504636963259354, 0.018118314520104855, 0.019233264489725756, 0.023277025938204417, 0.019091991363691614, 0.020495936876730597, 0.022535131086748067, 0.020381433132192782, 0.01829731716499092, 0.01803194829291645, 0.019534978894806515, 0.01634041697247165, 0.019031129864471294, 0.017034552406761497, 0.017623133404418494, 0.02250364672630053, 0.0178040875798604, 0.019851909744316353, 0.02480737199801239, 0.022247899407735337, 0.017768912040453708, 0.016606520087751268, 0.02016068585547879, 0.016158656124707703, 0.021130033010530406, 0.02417297704790903, 0.015395928766642027, 0.01959335882885404, 0.02141328169139375, 0.023526328384806568, 0.02092941018104284, 0.01760097447737223, 0.02339881521031409, 0.020094958815215093, 0.02010888884466533, 0.02253030207702178, 0.016479220357849565, 0.02319626719119277, 0.021832869060032574])
for _i, (_c, _r) in enumerate(zip(centers_pop_69c2dd2b, radii_pop_69c2dd2b)):
    _body = pre.rigidDisk(r=float(_r), center=_c, model=mod_rigid, material=mat_SAND, color='CYANx')
    bodies.addAvatar(_body)

# --- contact laws ---
law_st_sd = pre.tact_behav(name='st_sd', law='IQS_CLB', fric=0.35)
tacts.addBehav(law_st_sd)

# --- see tables ---
see_0 = pre.see_table(CorpsCandidat='RBDY2', candidat='DISKx', colorCandidat='BLUEx', CorpsAntagoniste='RBDY2', antagoniste='JONCx', colorAntagoniste='GRAYx', behav='st_sd', alert=0.05)
sees.addSeeTable(see_0)
see_1 = pre.see_table(CorpsCandidat='RBDY2', candidat='DISKx', colorCandidat='CYANx', CorpsAntagoniste='RBDY2', antagoniste='JONCx', colorAntagoniste='GRAYx', behav='st_sd', alert=0.05)
sees.addSeeTable(see_1)

# --- boundary conditions ---
av_e7b5a684.imposeDrivenDof(component=[1, 2, 3], dofty='vlocy', ct=0.0)

# --- post-processing ---
posts.addCommand(pre.postpro_command(name='SOLVER INFORMATIONS', step=20))

pre.writeDatbox(
    dim=2, mats=mats, mods=mods, tacts=tacts,
    sees=sees, bodies=bodies, post=posts,
)
