"""
command.py generated by lmgc90_core — project 'gui_headless'
dt=0.001  steps=500  solver=Stored_Delassus_Loops
"""
from pylmgc90 import chipy

chipy.Initialize()
chipy.SetDimension(2)
chipy.checkDirectories()
chipy.utilities_DisableLogMes()

chipy.ReadDatbox(deformable=False)

chipy.RBDY2_LoadTactors()
chipy.LoadTactors()
chipy.ReadIni()

chipy.SetTimeStep(0.001)
chipy.SetThetaIntegrator(0.5)
chipy.ComputeMass()

chipy.OpenDisplayFiles()
chipy.WriteDisplayFiles(0)

chipy.utilities_logMes('STARTING TIME LOOP')
for k in range(1, 500 + 1):
    chipy.IncrementStep()
    chipy.RBDY2_ComputeFext()
    chipy.RBDY2_ComputeBulk()
    chipy.ComputeFreeVelocity()
    chipy.SelectProxTactors()
    chipy.RecupRloc()
    chipy.ExSolver('Stored_Delassus_Loops         ', 'Quad ', 0.0001666, 1.0, 50, 1000)
    chipy.StockRloc()
    chipy.ComputeDof()
    chipy.RBDY2_ComputeRFext()
    chipy.UpdateStep()
    if k % 50 == 0:
        chipy.WriteOut(1)
    if k % 50 == 0:
        chipy.WriteDisplayFiles(1)

chipy.WriteLast()
chipy.CloseDisplayFiles()
chipy.Finalize()
