"""
pre.py generated by lmgc90_core — project 'gui_headless'
dimension = 2    units = SI
bodies    = 4  (AoS 4 + SoA 0)
"""
from pylmgc90 import pre
import numpy as np

mats   = pre.materials()
mods   = pre.models()
bodies = pre.avatars()
tacts  = pre.tact_behavs()
sees   = pre.see_tables()
posts  = pre.postpro_commands()

# --- materials ---
mat_STEEL = pre.material(name='STEEL', materialType='RIGID', density=7800.0)
mats.addMaterial(mat_STEEL)
mat_SAND = pre.material(name='SAND', materialType='RIGID', density=2500.0)
mats.addMaterial(mat_SAND)

# --- models ---
mod_rigid = pre.model(name='rigid', physics='MECAx', element='Rxx2D', dimension=2)
mods.addModel(mod_rigid)

# --- avatars (individually edited) ---
av_4c1647a7 = pre.rigidDisk(r=0.08, center=[0.0, 0.2], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_4c1647a7)

av_cdbd45ad = pre.rigidDisk(r=0.08, center=[0.25, 0.2], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_cdbd45ad)

av_24e9ae96 = pre.rigidDisk(r=0.08, center=[0.5, 0.2], model=mod_rigid, material=mat_SAND, color='BLUEx')
bodies.addAvatar(av_24e9ae96)

av_5898ebd4 = pre.smoothWall(l=1.2, h=0.08, center=[0.25, -0.04], model=mod_rigid, material=mat_STEEL, color='GRAYx', nb_polyg=12)
bodies.addAvatar(av_5898ebd4)

pre.writeDatbox(
    dim=2, mats=mats, mods=mods, tacts=tacts,
    sees=sees, bodies=bodies, post=posts,
)
