"""Pure demo scenes — depend only on ``Project`` / ``pre`` (no Qt, no engine)."""
from .demos import SCENE_BUILDERS, masonry_deformable_wall, cylinder_deposit_3d, mesh_rigids_from_file, cell_adhesion_v1, cell_adhesion_v2, cell_adhesion_v3, cell_adhesion_v4, cell_adhesion_v5
from .demos import (
    avalanche_slope,
    ball_bearing,
    biaxial_compression,
    cable_pendulum,
    circle_loop,
    cluster_pile,
    cohesive_wall,
    couette_shear,
    deformable_drop,
    deformable_impact,
    disc_brake,
    dof_conditions,
    dumbbell,
    factory_injection,
    falling_disks,
    for_loop_ramp,
    granulo_deposit,
    hexagon_packing,
    hopper_discharge,
    l_shaped_wall,
    masonry_wall,
    rotating_drum,
    sphere_stack,
)

__all__ = [
    "mesh_rigids_from_file",
    "cylinder_deposit_3d, mesh_rigids_from_file",
    "masonry_deformable_wall, cylinder_deposit_3d, mesh_rigids_from_file",
    "cell_adhesion_v5",
    "cell_adhesion_v4, cell_adhesion_v5",
    "cell_adhesion_v3, cell_adhesion_v4, cell_adhesion_v5",
    "cell_adhesion_v2",
    "cell_adhesion_v1",
    "SCENE_BUILDERS",
    "avalanche_slope",
    "ball_bearing",
    "biaxial_compression",
    "cable_pendulum",
    "circle_loop",
    "cluster_pile",
    "cohesive_wall",
    "couette_shear",
    "deformable_drop",
    "deformable_impact",
    "disc_brake",
    "dof_conditions",
    "dumbbell",
    "factory_injection",
    "falling_disks",
    "for_loop_ramp",
    "granulo_deposit",
    "hexagon_packing",
    "hopper_discharge",
    "l_shaped_wall",
    "masonry_wall",
    "rotating_drum",
    "sphere_stack",
]
